### ISSUE TITLE
Accept a predicate for lazy evaluation

### ISSUE THREAD

**Issue by inker** [kemitchell/boolean-json-eval.js#3]
Please, consider making an object accept predicate functions (the ones returning `true` or `false`) in addition to boolean values themselves. This would allow to lazily evaluate expressions that would otherwise be needed to be calculated first so that their result be used in the object argument.

**Comment by kemitchell** [comment]
I'm not quite sure what you mean, but I suspect the flexibility you're after rightly belongs in a different package.  This one is quite small, MIT-licensed, and in Standard Style.  You might use it as a starting point.
